SYS_RESTART_SYSCALL:        .int       0
SYS_EXIT:                   .int       1
SYS_FORK:                   .int       2
SYS_READ:                   .int       3
SYS_WRITE:                  .int       4
SYS_OPEN:                   .int       5
SYS_CLOSE:                  .int       6
SYS_CREAT:                  .int       8
SYS_LINK:                   .int       9
SYS_UNLINK:                 .int      10
SYS_EXECVE:                 .int      11
SYS_CHDIR:                  .int      12
SYS_TIME:                   .int      13
SYS_MKNOD:                  .int      14
SYS_CHMOD:                  .int      15
SYS_LCHOWN:                 .int      16
SYS_LSEEK:                  .int      19
SYS_GETPID:                 .int      20
SYS_MOUNT:                  .int      21
SYS_UMOUNT:                 .int      22
SYS_SETUID:                 .int      23
SYS_GETUID:                 .int      24
SYS_STIME:                  .int      25
SYS_PTRACE:                 .int      26
SYS_ALARM:                  .int      27
SYS_PAUSE:                  .int      29
SYS_UTIME:                  .int      30
SYS_ACCESS:                 .int      33
SYS_NICE:                   .int      34
SYS_SYNC:                   .int      36
SYS_KILL:                   .int      37
SYS_RENAME:                 .int      38
SYS_MKDIR:                  .int      39
SYS_RMDIR:                  .int      40
SYS_DUP:                    .int      41
SYS_PIPE:                   .int      42
SYS_TIMES:                  .int      43
SYS_BRK:                    .int      45
SYS_SETGID:                 .int      46
SYS_GETGID:                 .int      47
SYS_GETEUID:                .int      49
SYS_GETEGID:                .int      50
SYS_ACCT:                   .int      51
SYS_UMOUNT2:                .int      52
SYS_IOCTL:                  .int      54
SYS_FCNTL:                  .int      55
SYS_SETPGID:                .int      57
SYS_UMASK:                  .int      60
SYS_CHROOT:                 .int      61
SYS_USTAT:                  .int      62
SYS_DUP2:                   .int      63
SYS_GETPPID:                .int      64
SYS_GETPGRP:                .int      65
SYS_SETSID:                 .int      66
SYS_SIGACTION:              .int      67
SYS_SETREUID:               .int      70
SYS_SETREGID:               .int      71
SYS_SIGSUSPEND:             .int      72
SYS_SIGPENDING:             .int      73
SYS_SETHOSTNAME:            .int      74
SYS_SETRLIMIT:              .int      75
SYS_GETRLIMIT:              .int      76 /* BACK COMPAT 2GB LIMITED RLIMIT */
SYS_GETRUSAGE:              .int      77
SYS_GETTIMEOFDAY:           .int      78
SYS_SETTIMEOFDAY:           .int      79
SYS_GETGROUPS:              .int      80
SYS_SETGROUPS:              .int      81
SYS_SELECT:                 .int      82
SYS_SYMLINK:                .int      83
SYS_READLINK:               .int      85
SYS_USELIB:                 .int      86
SYS_SWAPON:                 .int      87
SYS_REBOOT:                 .int      88
SYS_READDIR:                .int      89
SYS_MMAP:                   .int      90
SYS_MUNMAP:                 .int      91
SYS_TRUNCATE:               .int      92
SYS_FTRUNCATE:              .int      93
SYS_FCHMOD:                 .int      94
SYS_FCHOWN:                 .int      95
SYS_GETPRIORITY:            .int      96
SYS_SETPRIORITY:            .int      97
SYS_STATFS:                 .int      99
SYS_FSTATFS:                .int     100
SYS_SOCKETCALL:             .int     102
SYS_SYSLOG:                 .int     103
SYS_SETITIMER:              .int     104
SYS_GETITIMER:              .int     105
SYS_STAT:                   .int     106
SYS_LSTAT:                  .int     107
SYS_FSTAT:                  .int     108
SYS_VHANGUP:                .int     111
SYS_SYSCALL:                .int     113 /* SYSCALL TO CALL A SYSCALL! */
SYS_WAIT4:                  .int     114
SYS_SWAPOFF:                .int     115
SYS_SYSINFO:                .int     116
SYS_IPC:                    .int     117
SYS_FSYNC:                  .int     118
SYS_SIGRETURN:              .int     119
SYS_CLONE:                  .int     120
SYS_SETDOMAINNAME:          .int     121
SYS_UNAME:                  .int     122
SYS_ADJTIMEX:               .int     124
SYS_MPROTECT:               .int     125
SYS_SIGPROCMASK:            .int     126
SYS_INIT_MODULE:            .int     128
SYS_DELETE_MODULE:          .int     129
SYS_QUOTACTL:               .int     131
SYS_GETPGID:                .int     132
SYS_FCHDIR:                 .int     133
SYS_BDFLUSH:                .int     134
SYS_SYSFS:                  .int     135
SYS_PERSONALITY:            .int     136
SYS_SETFSUID:               .int     138
SYS_SETFSGID:               .int     139
SYS__LLSEEK:                .int     140
SYS_GETDENTS:               .int     141
SYS__NEWSELECT:             .int     142
SYS_FLOCK:                  .int     143
SYS_MSYNC:                  .int     144
SYS_READV:                  .int     145
SYS_WRITEV:                 .int     146
SYS_GETSID:                 .int     147
SYS_FDATASYNC:              .int     148
SYS__SYSCTL:                .int     149
SYS_MLOCK:                  .int     150
SYS_MUNLOCK:                .int     151
SYS_MLOCKALL:               .int     152
SYS_MUNLOCKALL:             .int     153
SYS_SCHED_SETPARAM:         .int     154
SYS_SCHED_GETPARAM:         .int     155
SYS_SCHED_SETSCHEDULER:     .int     156
SYS_SCHED_GETSCHEDULER:     .int     157
SYS_SCHED_YIELD:            .int     158
SYS_SCHED_GET_PRIORITY_MAX: .int     159
SYS_SCHED_GET_PRIORITY_MIN: .int     160
SYS_SCHED_RR_GET_INTERVAL:  .int     161
SYS_NANOSLEEP:              .int     162
SYS_MREMAP:                 .int     163
SYS_SETRESUID:              .int     164
SYS_GETRESUID:              .int     165
SYS_POLL:                   .int     168
SYS_NFSSERVCTL:             .int     169
SYS_SETRESGID:              .int     170
SYS_GETRESGID:              .int     171
SYS_PRCTL:                  .int     172
SYS_RT_SIGRETURN:           .int     173
SYS_RT_SIGACTION:           .int     174
SYS_RT_SIGPROCMASK:         .int     175
SYS_RT_SIGPENDING:          .int     176
SYS_RT_SIGTIMEDWAIT:        .int     177
SYS_RT_SIGQUEUEINFO:        .int     178
SYS_RT_SIGSUSPEND:          .int     179
SYS_PREAD64:                .int     180
SYS_PWRITE64:               .int     181
SYS_CHOWN:                  .int     182
SYS_GETCWD:                 .int     183
SYS_CAPGET:                 .int     184
SYS_CAPSET:                 .int     185
SYS_SIGALTSTACK:            .int     186
SYS_SENDFILE:               .int     187
SYS_VFORK:                  .int     190
SYS_UGETRLIMIT:             .int     191 /* SUS COMPLIANT GETRLIMIT */
SYS_MMAP2:                  .int     192
SYS_TRUNCATE64:             .int     193
SYS_FTRUNCATE64:            .int     194
SYS_STAT64:                 .int     195
SYS_LSTAT64:                .int     196
SYS_FSTAT64:                .int     197
SYS_LCHOWN32:               .int     198
SYS_GETUID32:               .int     199
SYS_GETGID32:               .int     200
SYS_GETEUID32:              .int     201
SYS_GETEGID32:              .int     202
SYS_SETREUID32:             .int     203
SYS_SETREGID32:             .int     204
SYS_GETGROUPS32:            .int     205
SYS_SETGROUPS32:            .int     206
SYS_FCHOWN32:               .int     207
SYS_SETRESUID32:            .int     208
SYS_GETRESUID32:            .int     209
SYS_SETRESGID32:            .int     210
SYS_GETRESGID32:            .int     211
SYS_CHOWN32:                .int     212
SYS_SETUID32:               .int     213
SYS_SETGID32:               .int     214
SYS_SETFSUID32:             .int     215
SYS_SETFSGID32:             .int     216
SYS_GETDENTS64:             .int     217
SYS_PIVOT_ROOT:             .int     218
SYS_MINCORE:                .int     219
SYS_MADVISE:                .int     220
SYS_FCNTL64:                .int     221
SYS_GETTID:                 .int     224
SYS_READAHEAD:              .int     225
SYS_SETXATTR:               .int     226
SYS_LSETXATTR:              .int     227
SYS_FSETXATTR:              .int     228
SYS_GETXATTR:               .int     229
SYS_LGETXATTR:              .int     230
SYS_FGETXATTR:              .int     231
SYS_LISTXATTR:              .int     232
SYS_LLISTXATTR:             .int     233
SYS_FLISTXATTR:             .int     234
SYS_REMOVEXATTR:            .int     235
SYS_LREMOVEXATTR:           .int     236
SYS_FREMOVEXATTR:           .int     237
SYS_TKILL:                  .int     238
SYS_SENDFILE64:             .int     239
SYS_FUTEX:                  .int     240
SYS_SCHED_SETAFFINITY:      .int     241
SYS_SCHED_GETAFFINITY:      .int     242
SYS_IO_SETUP:               .int     243
SYS_IO_DESTROY:             .int     244
SYS_IO_GETEVENTS:           .int     245
SYS_IO_SUBMIT:              .int     246
SYS_IO_CANCEL:              .int     247
SYS_EXIT_GROUP:             .int     248
SYS_LOOKUP_DCOOKIE:         .int     249
SYS_EPOLL_CREATE:           .int     250
SYS_EPOLL_CTL:              .int     251
SYS_EPOLL_WAIT:             .int     252
SYS_REMAP_FILE_PAGES:       .int     253
SYS_SET_TID_ADDRESS:        .int     256
SYS_TIMER_CREATE:           .int     257
SYS_TIMER_SETTIME:          .int     258
SYS_TIMER_GETTIME:          .int     259
SYS_TIMER_GETOVERRUN:       .int     260
SYS_TIMER_DELETE:           .int     261
SYS_CLOCK_SETTIME:          .int     262
SYS_CLOCK_GETTIME:          .int     263
SYS_CLOCK_GETRES:           .int     264
SYS_CLOCK_NANOSLEEP:        .int     265
SYS_STATFS64:               .int     266
SYS_FSTATFS64:              .int     267
SYS_TGKILL:                 .int     268
SYS_UTIMES:                 .int     269
SYS_ARM_FADVISE64_64:       .int     270
SYS_PCICONFIG_IOBASE:       .int     271
SYS_PCICONFIG_READ:         .int     272
SYS_PCICONFIG_WRITE:        .int     273
SYS_MQ_OPEN:                .int     274
SYS_MQ_UNLINK:              .int     275
SYS_MQ_TIMEDSEND:           .int     276
SYS_MQ_TIMEDRECEIVE:        .int     277
SYS_MQ_NOTIFY:              .int     278
SYS_MQ_GETSETATTR:          .int     279
SYS_WAITID:                 .int     280
SYS_SOCKET:                 .int     281
SYS_BIND:                   .int     282
SYS_CONNECT:                .int     283
SYS_LISTEN:                 .int     284
SYS_ACCEPT:                 .int     285
SYS_GETSOCKNAME:            .int     286
SYS_GETPEERNAME:            .int     287
SYS_SOCKETPAIR:             .int     288
SYS_SEND:                   .int     289
SYS_SENDTO:                 .int     290
SYS_RECV:                   .int     291
SYS_RECVFROM:               .int     292
SYS_SHUTDOWN:               .int     293
SYS_SETSOCKOPT:             .int     294
SYS_GETSOCKOPT:             .int     295
SYS_SENDMSG:                .int     296
SYS_RECVMSG:                .int     297
SYS_SEMOP:                  .int     298
SYS_SEMGET:                 .int     299
SYS_SEMCTL:                 .int     300
SYS_MSGSND:                 .int     301
SYS_MSGRCV:                 .int     302
SYS_MSGGET:                 .int     303
SYS_MSGCTL:                 .int     304
SYS_SHMAT:                  .int     305
SYS_SHMDT:                  .int     306
SYS_SHMGET:                 .int     307
SYS_SHMCTL:                 .int     308
SYS_ADD_KEY:                .int     309
SYS_REQUEST_KEY:            .int     310
SYS_KEYCTL:                 .int     311
SYS_SEMTIMEDOP:             .int     312
SYS_VSERVER:                .int     313
SYS_IOPRIO_SET:             .int     314
SYS_IOPRIO_GET:             .int     315
SYS_INOTIFY_INIT:           .int     316
SYS_INOTIFY_ADD_WATCH:      .int     317
SYS_INOTIFY_RM_WATCH:       .int     318
SYS_MBIND:                  .int     319
SYS_GET_MEMPOLICY:          .int     320
SYS_SET_MEMPOLICY:          .int     321
SYS_OPENAT:                 .int     322
SYS_MKDIRAT:                .int     323
SYS_MKNODAT:                .int     324
SYS_FCHOWNAT:               .int     325
SYS_FUTIMESAT:              .int     326
SYS_FSTATAT64:              .int     327
SYS_UNLINKAT:               .int     328
SYS_RENAMEAT:               .int     329
SYS_LINKAT:                 .int     330
SYS_SYMLINKAT:              .int     331
SYS_READLINKAT:             .int     332
SYS_FCHMODAT:               .int     333
SYS_FACCESSAT:              .int     334
SYS_PSELECT6:               .int     335
SYS_PPOLL:                  .int     336
SYS_UNSHARE:                .int     337
SYS_SET_ROBUST_LIST:        .int     338
SYS_GET_ROBUST_LIST:        .int     339
SYS_SPLICE:                 .int     340
SYS_ARM_SYNC_FILE_RANGE:    .int     341
SYS_TEE:                    .int     342
SYS_VMSPLICE:               .int     343
SYS_MOVE_PAGES:             .int     344
SYS_GETCPU:                 .int     345
SYS_EPOLL_PWAIT:            .int     346
SYS_KEXEC_LOAD:             .int     347
SYS_UTIMENSAT:              .int     348
SYS_SIGNALFD:               .int     349
SYS_TIMERFD_CREATE:         .int     350
SYS_EVENTFD:                .int     351
SYS_FALLOCATE:              .int     352
SYS_TIMERFD_SETTIME:        .int     353
SYS_TIMERFD_GETTIME:        .int     354
SYS_SIGNALFD4:              .int     355
SYS_EVENTFD2:               .int     356
SYS_EPOLL_CREATE1:          .int     357
SYS_DUP3:                   .int     358
SYS_PIPE2:                  .int     359
SYS_INOTIFY_INIT1:          .int     360
SYS_PREADV:                 .int     361
SYS_PWRITEV:                .int     362
SYS_RT_TGSIGQUEUEINFO:      .int     363
SYS_PERF_EVENT_OPEN:        .int     364

